import { ThemeProvider } from '@gravity-ui/uikit';
import { getRootClassName } from '@gravity-ui/uikit/server';
import type { Metadata } from 'next';

import '@gravity-ui/uikit/styles/fonts.css';
import '@gravity-ui/uikit/styles/styles.css';
import '../style/common.scss';
import { notFound } from 'next/navigation';
import { NextIntlClientProvider } from 'next-intl';

import { routing } from '@/shared/lib/i18n/routing';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const theme = 'light';

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${getRootClassName({ theme })}`}>
        <NextIntlClientProvider messages={messages}>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
